# fly.toml app configuration file generated for slipway-self-host on 2025-02-18T09:03:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slipway-self-host'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-2x'
memory = '1gb'
